import asyncio
import asyncio

from typing import Callable
from grpclib.client import Channel

# generated by protoc
# python -m grpc_tools.protoc -I . --python_betterproto_out=frontend\src\betterproto proto\service.proto
from .betterproto.bone_generator import BoneGeneratorStub, Members

class RpcHandler:
    @classmethod
    def rpc_async_req(cls, members: dict, callback: Callable):
        with Channel('127.0.0.1', 50051) as channel:
            service = BoneGeneratorStub(channel)
            call_future = asyncio.create_task(service.execute(Members(members)))
            call_future.add_done_callback(callback)